```{r}
library(tidyverse)
library(haven)

PLS_data <- readRDS(file="../data/PLS_data.dta")
BIT_data <- readRDS(file="../data/BIT_data.dta")
media_wave_1 <- readRDS(file="../data/media_wave_1.dta")
media_wave_6 <- readRDS(file="../data/media_wave_6.dta")
demography <- readRDS(file="../data/demography.dta")
```

## wave 1 to wave 6 media to pls - for mom and dad

```{r}
glimpse(PLS_data)

pls_mom_1 <- PLS_data %>% 
  filter(par_id < 30000, wave = 1) %>%
  select(child_id, par_id, total_score)

pls_mom_6 <- PLS_data %>% 
  filter(par_id < 30000, wave = 6) %>%
  select(child_id, par_id, total_score)
  
pls_dad_1 <- PLS_data %>%
  filter(par_id > 30000, wave = 1) %>%
  select(child_id, par_id, total_score)
  
pls_dad_6 <- PLS_data %>%
  filter(par_id > 30000, wave = 6) %>%
  select(child_id, par_id, total_score)


media_mom_1 <- media_wave_1 %>%
  filter(par_id < 30000) %>%
  select(child_id, par_id, daily_use)

media_mom_6 <- media_wave_6 %>%
  filter(par_id < 30000) %>%
  select(child_id, par_id, daily_use)

media_dad_1 <- media_wave_1 %>% 
  filter(par_id > 30000) %>%
  select(child_id, par_id, daily_use)

media_dad_6 <- media_wave_6 %>% 
  filter(par_id > 30000) %>%
  select(child_id, par_id, daily_use)
```

