---
title: "aubree-updated-lmer-models"
output: html_document
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forcats)
library(haven)
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(janitor)
```

##Read Data 
```{r}
#PLS_data <- readRDS(file="../data/PLS_data.dta")
demography <- readRDS(file="../data/demography.dta")
media_long <- readRDS(file="../data/media_long.dta")
grouping_data <- readRDS(file = "../data/grouping_data.dta")


PLS_w4 <- read_excel("../data/wave-4-(18-mo)/PLS_W4_Final.xlsx", sheet = "PLS_ALL_W4")
PLS_w4 <- clean_names(PLS_w4)
PLS_w4 <-  PLS_w4 %>% 
  mutate(child_id = as.character(childid),
         par_id = as.character(parid),
        language= as.factor(case_when(
          language == 0 ~ "english",
          language == 1 ~ "spanish"
        )),
        site = as.factor(case_when(
          site == 1 ~ "umd",
          site == 2 ~ "uci"
        )))
PLS_w4 <- PLS_w4 %>%
  select(child_id, par_id, language, auditory_comprehension_score = plsacss, expressive_communication_score = plsecss, total_score = plsss, percentile_rank_expressive = plsecpr, percentile_rank_auditory = plsacpr, 
         percentile_rank_total = plspr)




PLS_w6 <- read_excel("../data/wave-6-(24-mo)/PLS_W6.xlsx",sheet = "PLS_ALL_W6")
PLS_w6 <- clean_names(PLS_w6)
PLS_w6 <-  PLS_w6 %>% 
  mutate(child_id = as.character(childid),
         par_id = as.character(parid),
        language= as.factor(case_when(
          language == 0 ~ "english",
          language == 1 ~ "spanish"
        )),
        site = as.factor(case_when(
          site == 1 ~ "umd",
          site == 2 ~ "uci"
        )))
PLS_w6 <- PLS_w6 %>%
  select(child_id, par_id, language, auditory_comprehension_score = plsacss, expressive_communication_score = plsecss, total_score = plsss, percentile_rank_expressive = plsecpr, percentile_rank_auditory = plsacpr, 
         percentile_rank_total = plspr)


PLS_w1 <- read_dta("../data/wave-1-(9-mo)/26_PLS_w1.dta")
PLS_w1 <- clean_names(PLS_w1)
PLS_w1 <-  PLS_w1 %>% 
  mutate(child_id = as.character(childid),
         par_id = as.character(parid),
         father = pargen == 1,
        language_26_PLS_w1 = as.factor(case_when(
          language_26_pls_w1 == 0 ~ "english",
          language_26_pls_w1 == 1 ~ "spanish"
        )),
        site = as.factor(case_when(
          site == 1 ~ "UMD",
          site == 2 ~ "UCI"
        )))
PLS_w1 <- PLS_w1 %>%
  select(child_id, par_id, father, language = language_26_PLS_w1, auditory_comprehension_score = plsacss, expressive_communication_score = plsecss, total_score = plsss, percentile_rank_expressive = plsecpr, percentile_rank_auditory = plsacpr, percentile_rank_total = plspr)
```


## Create fewer data sets combineing EVERYTHING, then we will only have a few 
## data sets to work with
```{r}

pls_wide <- full_join(pls_wide_mother, pls_wide_father)
media_wide <- readRDS(file="../data/media_wide.dta")


media_pls <- inner_join(media_wide, pls_wide, by = c("child_id", "par_id")) %>% filter(total_score.1 >0, total_score.4 > 0, total_score.6 >0)

PLS_W1 <- read_dta("../data/wave-1-(9-mo)/26_PLS_w1.dta")
PLS_W1 <- clean_names(PLS_W1) 
PLS_W1 <- PLS_W1 %>% 
  select(child_id = childid, par_id = parid, 
         auditory_comprehension_score = plsacss,
         expressive_communication_score = plsecss,
         total_score = plsss, percentile_rank = plspr,
         auditory_comprehension_percentile = plsacpr,
         expressive_communication_percentile = plsecpr)


PLS_w4 <- read_excel("../data/wave-4-(18-mo)/PLS_W4_Final.xlsx", sheet = "PLS_ALL_W4")
PLS_W4 <- clean_names(PLS_w4)
PLS_W4 <-  PLS_W4 %>% 
  select(child_id = childid, par_id = parid, language,
         auditory_comprehension_score = plsacss,
         expressive_communication_score = plsecss,
         total_score = plsss, percentile_rank = plspr,
         auditory_comprehension_percentile = plsacpr,
         expressive_communication_percentile = plsecpr)



PLS_w6 <- read_excel("../data/wave-6-(24-mo)/PLS_W6.xlsx",sheet = "PLS_ALL_W6")
PLS_w6 <- clean_names(PLS_w6)
PLS_w6 <-  PLS_w6 %>% 
  mutate(child_id = as.double(childid),
         par_id = as.double(parid),
        language= as.factor(case_when(
          language == 0 ~ "english",
          language == 1 ~ "spanish")))
PLS_w6 <- PLS_w6 %>%
  select(child_id, par_id, language, auditory_comprehension_score = plsacss, expressive_communication_score = plsecss, total_score = plsss, percentile_rank = plspr, auditory_comprehension_percentile = plsacpr, expressive_communication_percentile = plsecpr)

pls_total <-inner_join(PLS_W1, PLS_W4, by = c("child_id", "par_id"))
pls_all <-inner_join(pls_total, PLS_w6, by = c("child_id", "par_id"))
pls_all <- pls_all %>% 
  filter(percentile_rank.x >0,
         percentile_rank >0,
         percentile_rank.y >0) %>% 
    mutate(child_id = as.character(child_id),
           par_id = as.character(par_id))
media_wide <- media_wide %>% 
  mutate(child_id = as.character(child_id))
media_pls <- inner_join(pls_all, media_wide, by = c("child_id", "par_id"))

media_pls_lmer <- 
  inner_join(media_pls, grouping_data, by = "child_id")
## note  x = 1, y = 4, and blank = 6

test <- media_pls_lmer %>% 
  select(child_id, par_id, percentile_rank.x, auditory_comprehension_percentile.x, expressive_communication_percentile.x, language.x, behavior_management.1, mealtimes.1) %>% 
  mutate(percentile_rank = percentile_rank.x,
         auditory_comprehension_percentile = auditory_comprehension_percentile.x, 
         expressive_communication_percentile = expressive_communication_percentile.x,
         language = as.factor(language.x),
         meal_times = mealtimes.1,
         behavior_management = behavior_management.1,
           wave = 1)

test2 <- media_pls_lmer %>% 
   select(child_id, par_id, percentile_rank.y, auditory_comprehension_percentile.y, expressive_communication_percentile.y, language.y, behavior_management.4, mealtimes.4) %>% 
  mutate(percentile_rank = percentile_rank.y, auditory_comprehension_percentile = auditory_comprehension_percentile.y, 
         expressive_communication_percentile = expressive_communication_percentile.y,
         language = as.factor(language.y),
         meal_times = mealtimes.4,
         behavior_management = behavior_management.4,
         wave = 4)
  
testlong <- full_join(test, test2)

test3 <- media_pls_lmer %>% 
   select(child_id, par_id, percentile_rank, auditory_comprehension_percentile, expressive_communication_percentile, behavior_management.6, mealtimes.6) %>% 
  mutate(meal_times = mealtimes.6,
         behavior_management = behavior_management.6,
         wave = 6)

test2long <- full_join(testlong, test3)


media_pls_lmer <- test2long %>% 
  select(child_id, par_id, percentile_rank, expressive_communication_percentile, auditory_comprehension_percentile, language, wave, behavior_management, meal_times)

media_pls_lmer <- full_join(media_pls_lmer, grouping_data)

```

## We will only need to pay attention to demography and media_pls_lmer data set


## Let create models 
```{r}
library(lme4)
library(lmerTest)
model <- lmer(percentile_rank ~ daily_use * wave + (1|child_id) + condition, 
              data = long_boi_2)
summary(model)
```



