---
title: "lost"
author: "James"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(forcats)
library(haven)
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(janitor)
```

```{r}
media_data <- readRDS(file="../data/media_data.dta")
demography <- readRDS(file="../data/demography.dta")

pls_long <- readRDS(file="../data/PLS_long_mother.dta")
pls_long_father <- readRDS(file="../data/PLS_long_father.dta")
bit_long_par <- readRDS(file="../data/BIT_long_par.dta")
bit_long_father <- readRDS(file="../data/BIT_long_father.dta")
bit_long_mother <- readRDS(file="../data/BIT_long_mother.dta")

pls_wide <- readRDS(file="../data/PLS_wide.dta")
bit_wide <- readRDS(file="../data/BIT_wide.dta")

media_long <- readRDS(file="../data/media_long.dta")
media_wide <- readRDS(file="../data/media_wide.dta")

pls_wide %>% 
  filter(total_score.4 >= 0)
```

```{r}
library(forcats)
library(haven)
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(janitor)
```

```{r}
media_data <- readRDS(file="../data/media_data.dta")
demography <- readRDS(file="../data/demography.dta")

pls_long <- readRDS(file="../data/PLS_long_mother.dta")
pls_long_father <- readRDS(file="../data/PLS_long_father.dta")
bit_long_par <- readRDS(file="../data/BIT_long_par.dta")
bit_long_father <- readRDS(file="../data/BIT_long_father.dta")
bit_long_mother <- readRDS(file="../data/BIT_long_mother.dta")

pls_wide <- readRDS(file="../data/PLS_wide.dta")
bit_wide <- readRDS(file="../data/BIT_wide.dta")

media_long <- readRDS(file="../data/media_long.dta")
media_wide <- readRDS(file="../data/media_wide.dta")

pls_wide %>% 
  filter(total_score.4 >= 0)
```

## Bootstrap with mixed effect random slope

```{r}
pls <- readRDS("../data/PLS_long_mother.dta")
media <- readRDS("../data/media_long.dta")
pls_wide <- readRDS("../data/PLS_wide_mother.dta")

pls_wide <- pls_wide %>% 
  filter(total_score.1 >= 0,
         total_score.6 >= 0)

tmp1 <- pls_wide %>% 
  select(child_id, par_id, total_score.1) %>% 
  mutate(total_score = total_score.1)
tmp2 <- pls_wide %>% 
  select(child_id, par_id, total_score.2) %>% 
  mutate(total_score = total_score.2)
pls_long <- full_join(tmp1, tmp2)
  
pls <- pls %>% 
  mutate(wave = as.factor(wave),
         total_score = ifelse(total_score < 0, NA, total_score)) %>% 
  select(par_id, child_id, wave, total_score)

media <- media %>% 
  mutate(wave = as.factor(wave),
         daily_use = ifelse(daily_use < 0, NA, daily_use)) %>% 
  select(par_id, child_id, wave, daily_use) %>%
  filter(par_id < 30000, wave != 4)


media_pls <- media %>%
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  select(par_id, child_id, daily_use, total_score, wave) %>%
  na.omit()


bootstrap <- function(df, func, num) {
  temp <- numeric(num)
  # setup
  for (i in 1:num) {
    # repeated action
    # sampling
    lying_mothers <- df[sample(nrow(df), 450, replace = TRUE), ]
    
    # model
    model <- func(total_score ~ daily_use * wave + (1 + wave | child_id), data = lying_mothers, REML = FALSE)
    
    temp[i] <- cor(lying_mothers$total_score, predict(model, newdata = lying_mothers))
    
  }
  
  #ci <- quantile(temp, prob = c(0.025, 0.975), na.rm = TRUE)
  #list(est=func(temp), ci=ci)
  print(temp)
  print(mean(temp))
}

#bootstrap(media_pls, lmer, 10)


lying_mothers <- media_pls[sample(nrow(media_pls), 110), ] %>% 
  rbind(media_pls)
# clean data

# lying_mothers %>% 
#   arrange(child_id)

model <- lmer(total_score ~ daily_use * wave + (1 + daily_use| child_id), data = lying_mothers, REML = FALSE)

summary(model)

# create data set without NA values to be used for predictions
#media_pred <- lying_mothers %>%
#  filter(!is.na(daily_use), !is.na(total_score))

# graph actual vs predicted
lying_mothers %>%
  mutate(pred = predict(model, newdata = lying_mothers)) %>%
  ggplot(aes(total_score, predict(model, newdata = lying_mothers))) +
  geom_point() +
  geom_abline(intercept = 0,
              slope = 1,
              col = "salmon") +
  labs(x = "Acutal Total PLS Score",
       y = "Predicted Total PLS Score",
       title = "Actual vs Predicted PLS Scores")

cor(lying_mothers$total_score, predict(model, newdata = lying_mothers))

```

## Aubree's original model
```{r}
library(lme4)
library(lmerTest)
```

```{r}
pls <- readRDS("../data/pls_long_rank.dta")
media <- readRDS("../data/media_long.dta")
grouping_data <- readRDS(file = "../data/grouping_data.dta")

# colSums(is.na(pls))
# colSums(is.na(media))

pls <- pls %>% 
  mutate(wave = as.factor(wave),
          total_score = ifelse(plspr < 0, NA, plspr)) %>% 
  select(par_id, child_id, wave, total_score) %>% 
  mutate(child_id = as.character(child_id),
         par_id = as.character(par_id))

media <- media %>% 
  mutate(wave = as.factor(wave),
         mealtimes = ifelse(mealtimes < 0, NA, mealtimes),
         behavior_management = ifelse(behavior_management < 0, NA, behavior_management),
         daily_use = ifelse(daily_use < 0, NA, daily_use))
  # select(par_id, child_id, wave, daily_use)
  # filter(par_id < 30000, wave != 4)


media_pls <- media %>%
  full_join(pls, by = c("par_id", "child_id", "wave"))
  # select(par_id, child_id, daily_use, total_score, wave)
   #filter(total_score < 150) %>% 

# demography
demography <- readRDS(file="../data/demography.dta")
```


```{r}
media_pls_demo1 <- left_join(media_pls, demography, by = c("par_id", "child_id"))

media_pls_demo <- media_pls_demo1 %>% 
  left_join(grouping_data, by = "child_id") %>% 
  mutate(child_id = as.factor(child_id),
         years_school_complete = as.factor(years_school_complete),
         condition = as.factor(condition),
         wave = as.factor(wave),
         father = as.integer(par_id) >= 30000) %>% 
  select(child_id, par_id, wave, total_score, behavior_management, condition, father, highest_degree_completed) %>% 
    na.omit()



model <- media_pls_demo %>% 
  lmer(total_score ~  behavior_management*wave + condition +father+ (1 + behavior_management| child_id:condition), data = .)
summary(model)
cor(media_pls_demo$total_score, predict(model, newdata = media_pls_demo))

```


```{r}

# qqnorm(resid(model)) 
# qqline(resid(model), col = "red") 
# 
# library(MuMIn)
# r.squaredGLMM(model)
library(equatiomatic)
extract_eq(model)
```
$$
\begin{aligned}
  \operatorname{total\_score}_{i}  &\sim N \left(\mu, \sigma^2 \right) \\
    \mu &=\alpha_{j[i]} + \beta_{1}(\operatorname{mealtimes}) + \beta_{2}(\operatorname{wave}_{\operatorname{6}}) + \beta_{3}(\operatorname{wave}_{\operatorname{4}}) \\
    \alpha_{j}  &\sim N \left(\mu_{\alpha_{j}}, \sigma^2_{\alpha_{j}} \right)
    \text{, for child\_id j = 1,} \dots \text{,J}
\end{aligned}
$$

```{r}
# graph actual vs predicted
media_pls %>%
  mutate(pred = predict(model, newdata = lying_mothers)) %>%
  ggplot(aes(total_score, predict(model, newdata = media_pls))) +
  geom_point() +
  geom_abline(intercept = 0,
              slope = 1,
              col = "salmon") +
  labs(x = "Acutal Total PLS Score",
       y = "Predicted Total PLS Score",
       title = "Actual vs Predicted PLS Scores")


```

$$
\begin{aligned}
  \operatorname{total\_score}_{i}  &\sim N \left(\mu, \sigma^2 \right) \\
    \mu &=\alpha_{j[i]} + \beta_{1}(\operatorname{daily\_use}) + \beta_{2}(\operatorname{wave}_{\operatorname{6}}) + \beta_{3}(\operatorname{daily\_use} \times \operatorname{wave}_{\operatorname{6}}) \\
    \alpha_{j}  &\sim N \left(\mu_{\alpha_{j}}, \sigma^2_{\alpha_{j}} \right)
    \text{, for child\_id j = 1,} \dots \text{,J}
\end{aligned}
$$

# copy from Chandra's 
```{r}
library(lme4)
library(lmerTest)
pls <- readRDS("../data/pls_long_rank.dta")
bit_mother <- readRDS("../data/BIT_long_mother.dta")
bit_father <- readRDS("../data/BIT_long_father.dta")
bit <- readRDS("../data/BIT_long_par.dta")
demo <- readRDS("../data/demography.dta")
media <- readRDS("../data/media_long.dta")
grouping <- readRDS("../data/grouping_data.dta")



# demo <- demo %>% 
#   transmute(par_id, child_id, 
#             bill_difficulty = as.factor(bill_difficulty),
#             marital_status = as.factor(marital_status),
#             assistance,
#             father)

#library(naniar)
#vis_miss(demo)

grouping <- grouping %>% 
  mutate(treatment = case_when(
    condition == "4" ~ " - control",
    condition == "1" ~ " - mom",
    condition == "2" ~ " - dad",
    condition == "3" ~ " - both"),
    treatment = fct_relevel(
      treatment,
      " - control",
      " - mom",
      " - dad",
      " - both"),
    control = ifelse(condition == "4", TRUE, FALSE))

pls <- pls %>%
  mutate(par_id = as.character(par_id),
         child_id = as.character(child_id))
pls %>% 
  filter(wave == 6) %>% 
  nrow()

media_pls <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id"))

media_pls_mother <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id")) %>%
  filter(par_id < 30000)

media_pls_father <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id")) %>%
  filter(par_id >= 30000)
 
demographic_background <- read_dta("../data/wave-1-(9-mo)/1_DEM_w1.dta")
media_pls <- media_pls %>% 
  inner_join(transmute(demographic_background, par_age = parage,
    child_id = as.character(childid),
      par_id = as.character(parid)), by = c("child_id", "par_id"))

media_pls1 <- media_pls %>% 
  select(plspr, behavior_management, father,wave, treatment , par_age, years_school_complete, span_lang_form, child_id) %>% 
  na.omit()

model <- media_pls1 %>% 
  lmer(plspr ~ behavior_management+ father+wave+ treatment + par_age+ years_school_complete+ span_lang_form+ (1 | child_id), REML = FALSE, data = .)

summary(model)

library(ggplot2)
library(MuMIn)
MuMIn::r.squaredGLMM(model)
media_pls1 %>%
#  mutate(pred = predict(model, newdata = media_pls)) %>%
  ggplot(aes(plspr, predict(model, newdata = media_pls1))) +
  geom_point() +
  geom_abline(intercept = 0,
              slope = 1,
              col = "salmon") +  
  scale_y_continuous(expand=c(0,0), limits = c(0, 100))+
  scale_x_continuous(expand=c(0,0), limits = c(0, 100))+
  theme_bw()+
  labs(y = "Acutal Total PLS Percentile Rank",
       x = "Predicted Total PLS Percentile Rank",
       title = "Actual vs Predicted PLS Percentile Rank",
       caption = "Correlation: 0.819")

cor(media_pls1$plspr, predict(model, newdata = media_pls1))

library(equatiomatic)
```