

# Data

##libraries
```{r}
library(forcats)
library(haven)
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(janitor)
library(magrittr)
library(ggcorrplot)

library(tidyverse)
library(haven)
library(lme4)
library(lmerTest)
library(nlme)
```

## data loading
```{r}
pls <- readRDS("../data/pls_long_rank.dta")
bit_mother <- readRDS("../data/BIT_long_mother.dta")
bit_father <- readRDS("../data/BIT_long_father.dta")
bit <- readRDS("../data/BIT_long_par.dta")
demo <- readRDS("../data/demography.dta")
media <- readRDS("../data/media_long.dta")
grouping <- readRDS("../data/grouping_data.dta")
#hhincome, pargen, childid, parid
background <- read_dta("../data/wave-1-(9-mo)/2_BCK_w1.dta")
demographic_background <- read_dta("../data/wave-1-(9-mo)/1_DEM_w1.dta")
```

## data wrangling
```{r}

bg_income <- background %>% 
  zap_labels() %>% 
  transmute(par_id = as.character(parid),
            child_id = as.character(childid),
            hhincome = as.numeric(hhincome),
            household_income = hhincome/1000,
            father = as.logical(pargen))

bg_age <- demographic_background %>% 
  zap_labels() %>% 
  transmute(par_id = as.character(parid),
            child_id = as.character(childid),
            parent_age = as.numeric(parage),
            father = as.logical(pargen))


# if hhincome isn't a good predictor let's include bill_difficulty
demo <- demo %>% 
   transmute(par_id, 
             child_id, 
             bill_difficulty = as.factor(bill_difficulty),
             marital_status = as.factor(marital_status),
             assistance,
             father,
             par_us_born,
             highest_degree_completed,
             span_lang_form)

grouping <- grouping %>% 
  mutate(treatment = case_when(
    condition == "4" ~ " - control",
    condition == "1" ~ " - mom",
    condition == "2" ~ " - dad",
    condition == "3" ~ " - both"),
    treatment = fct_relevel(
      treatment,
      " - control",
      " - mom",
      " - dad",
      " - both"),
    control = ifelse(condition == "4", TRUE, FALSE))

pls <- pls %>%
  zap_labels() %>% 
  mutate(par_id = as.character(par_id),
         child_id = as.character(child_id))
 

media_pls <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id")) %>% 
  inner_join(bg_age, by = c("child_id", "par_id")) %>% 
  inner_join(bg_income, by = c("child_id", "par_id"))

media_pls_mother <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id")) %>%
  inner_join(bg_age, by = c("child_id", "par_id")) %>% 
  inner_join(bg_income, by = c("child_id", "par_id")) %>% 
  filter(par_id < 30000)

media_pls_father <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id")) %>%
  inner_join(bg_age, by = c("child_id", "par_id")) %>% 
  inner_join(bg_income, by = c("child_id", "par_id")) %>% 
  filter(par_id >= 30000)
```



# model

```{r}
model <- lmer(plspr ~ behavior_management:father:wave + condition + (1 | child_id), REML = FALSE, data = media_pls)

summary(model)
```

Main Effect Additions to Model:
Listed here are variables that need to be included in the model because they hold such important weight in the literature it’s non-negotiable
 * Parent_education
 * Parage
 * Nativity and/or lang_form (look out for collinearity, if it exists too just much select one)
 * Behavior_management


```{r}
#+ treatment + wave + par_us_born
model <- lmer(plspr ~ behavior_management  + parent_age + father  + span_lang_form + highest_degree_completed + behavior_management:treatment + (1 | child_id), REML = FALSE, data = media_pls)

summary(model)
```


