---
title: "aubree-homoscedasticity"
author: "Aubree Krager"
date: "8/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Get libraries
```{r}
library(forcats)
library(haven)
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(janitor)
library(magrittr)
library(ggcorrplot)
library(viridis)
library(haven)
library(lme4)
library(lmerTest)
library(nlme)
library(car) # for levene's test for Homo of Var
#install.packages("car")
require("lattice")
#install.packages("effects")
library(effects)
#install.packages("sjPlot")
library(sjPlot)
#install.packages("glmmTMB")
install.packages("robustlmm")
library(robustlmm)
```

#run this chunk for the data and model
```{r}
# copy from Chandra's 
pls <- readRDS("../data/pls_long_rank.dta")
bit_mother <- readRDS("../data/BIT_long_mother.dta")
bit_father <- readRDS("../data/BIT_long_father.dta")
bit <- readRDS("../data/BIT_long_par.dta")
demo <- readRDS("../data/demography.dta")
media <- readRDS("../data/media_long.dta")
grouping <- readRDS("../data/grouping_data.dta")



# demo <- demo %>% 
#   transmute(par_id, child_id, 
#             bill_difficulty = as.factor(bill_difficulty),
#             marital_status = as.factor(marital_status),
#             assistance,
#             father)

#library(naniar)
#vis_miss(demo)

grouping <- grouping %>% 
  mutate(treatment = case_when(
    condition == "4" ~ " - control",
    condition == "1" ~ " - mom",
    condition == "2" ~ " - dad",
    condition == "3" ~ " - both"),
    treatment = fct_relevel(
      treatment,
      " - control",
      " - mom",
      " - dad",
      " - both"),
    control = ifelse(condition == "4", TRUE, FALSE))

pls <- pls %>%
  mutate(par_id = as.character(par_id),
         child_id = as.character(child_id))
pls %>% 
  filter(wave == 6) %>% 
  nrow()

media_pls <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id"))

media_pls_mother <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id")) %>%
  filter(par_id < 30000)

media_pls_father <- media %>%
  full_join(bit, by = c("child_id", "wave")) %>% 
  full_join(pls, by = c("par_id", "child_id", "wave")) %>%
  inner_join(grouping, by = c("child_id")) %>%
  inner_join(demo, by = c("child_id", "par_id")) %>%
  filter(par_id >= 30000)
 
demographic_background <- read_dta("../data/wave-1-(9-mo)/1_DEM_w1.dta")
media_pls <- media_pls %>% 
  inner_join(transmute(demographic_background, par_age = parage,
    child_id = as.character(childid),
      par_id = as.character(parid)), by = c("child_id", "par_id"))

media_pls1 <- media_pls %>% 
  select(plspr, behavior_management, father,wave, treatment , par_age, years_school_complete, span_lang_form, child_id) %>% 
  na.omit()

model <- media_pls1 %>% 
  lmer(plspr ~ behavior_management+ father+wave+ treatment + par_age+ years_school_complete+ span_lang_form+ (1 | child_id), REML = FALSE, data = .)

summary(model)
```

#Reestimate the model with robust errors
```{r}
robustmodel <- media_pls1 %>% 
  rlmer(plspr ~ behavior_management+ father+wave+ treatment + par_age+ years_school_complete+ span_lang_form+ (1 | child_id), REML = FALSE, data = .)

summary(robustmodel)
```

Note there is a slight change in estimates and standard errors. 


